"""
remove_fp.py - 从Xbench报告中删除对照文件标记为误报的条目

Usage:
    python remove_fp.py --ref <对照文件> --input <待处理文件> [--output <输出路径>]

支持 .xls / .xlsx。复制待处理文件后在其副本上删行，保留原文件所有样式。
匹配: source_text + target_text 完全一致
标记: Comments列含 "误报" / "FE" / "false positive" / "FP"（大小写不敏感）
"""

import sys, os, re, argparse, shutil

FP_KEYWORDS = ["误报", "FE", "false positive", "FP"]

_RE_DATA_ROW = re.compile(r".+\s+\(\d+\)$")
_RE_TERM_PAIR = re.compile(r"\([^)]*/.+\)")

_SKIP_PREFIXES = (
    "Exported QA Report", "ApSIC XBench", "http://",
    "Selected QA Checks", "Basic", "Content",
    "Key Term Glossaries", "Checklists", "Generated by",
    "Source", "Target", "Comments", "Metadata", "Project Checklist",
)

_KNOWN_CHECK_TYPES = [
    "Key Term Mismatch",
    "Inconsistency in Source",
    "Inconsistency in Target",
    "Untranslated Segments",
    "Target same as Source",
    "Tag Mismatch",
    "Numeric Mismatch",
    "URL Mismatch",
    "Alphanumeric Mismatch",
    "ALLUPPERCASE Mismatch",
    "CamelCase Mismatch",
    "Leading/Trailing Mismatch",
    "Unpaired Symbol",
    "Unpaired Quotes",
    "Double Blank",
    "Repeated Word",
    "Repeated Words",
    "Segments with Comments",
]


def clean(val):
    if val is None:
        return ""
    return str(val).strip()


def is_group_header(a):
    if _RE_DATA_ROW.match(a):
        return False
    if _RE_TERM_PAIR.search(a):
        return True
    low = a.lower()
    if any(low.startswith(ct.lower()) for ct in _KNOWN_CHECK_TYPES):
        return True
    # Catch custom check types not in the hardcoded list
    # (e.g. ALLUPPERCASE Mismatch, CamelCase Mismatch)
    if 'mismatch' in low:
        return True
    return False


def is_skip(a):
    if not a:
        return True
    return any(a.lower().startswith(p.lower()) for p in _SKIP_PREFIXES)


def is_data_row(a):
    return bool(_RE_DATA_ROW.match(a))


def is_fp(comment):
    return any(kw.lower() in clean(comment).lower() for kw in FP_KEYWORDS)


# ═══════════════════════════════════════════════════════════════
# Analysis (library-agnostic row classification)
# ═══════════════════════════════════════════════════════════════

def get_fp_triples_xlrd(ws):
    """Extract FP (st,tt,check_type) triples from reference file (.xls, xlrd, 0-idx)."""
    triples = set()
    current_ct = ""
    for r in range(11, ws.nrows):
        a = clean(ws.cell_value(r, 0))
        if is_group_header(a):
            current_ct = a
            continue
        if is_skip(a):
            continue
        if is_data_row(a):
            if any(is_fp(ws.cell_value(r, c)) for c in range(4, ws.ncols)):
                st = clean(ws.cell_value(r, 2))
                tt = clean(ws.cell_value(r, 3))
                triples.add((st, tt, current_ct))
    return triples


def get_fp_triples_openpyxl(ws):
    """Extract FP (st,tt,check_type) triples from reference file (.xlsx, openpyxl, 1-idx)."""
    triples = set()
    current_ct = ""
    for r in range(11, ws.max_row + 1):
        a = clean(ws.cell(r, 1).value)
        if is_group_header(a):
            current_ct = a
            continue
        if is_skip(a):
            continue
        if is_data_row(a):
            if any(is_fp(ws.cell(r, c).value) for c in range(5, ws.max_column + 1)):
                st = clean(ws.cell(r, 3).value)
                tt = clean(ws.cell(r, 4).value)
                triples.add((st, tt, current_ct))
    return triples


def classify_rows_xlrd(ws):
    """Classify rows in .xls target (xlrd, 0-idx).
    Returns [(row_0idx, type, st, tt, check_type), ...]."""
    info = []
    current_ct = ""
    for r in range(11, ws.nrows):
        a = clean(ws.cell_value(r, 0))
        if is_group_header(a):
            current_ct = a
            info.append((r, 'header', '', '', current_ct))
        elif is_skip(a):
            info.append((r, 'skip', '', '', ''))
        elif is_data_row(a):
            info.append((r, 'data',
                         clean(ws.cell_value(r, 2)),
                         clean(ws.cell_value(r, 3)),
                         current_ct))
        else:
            info.append((r, 'unknown', '', '', ''))
    return info


def classify_rows_openpyxl(ws):
    """Classify rows in .xlsx target (openpyxl, 1-idx).
    Returns [(row_0idx, type, st, tt, check_type), ...]."""
    info = []
    current_ct = ""
    for r in range(11, ws.max_row + 1):
        a = clean(ws.cell(r, 1).value)
        if is_group_header(a):
            current_ct = a
            info.append((r - 1, 'header', '', '', current_ct))
        elif is_skip(a):
            info.append((r - 1, 'skip', '', '', ''))
        elif is_data_row(a):
            info.append((r - 1, 'data',
                         clean(ws.cell(r, 3).value),
                         clean(ws.cell(r, 4).value),
                         current_ct))
        else:
            info.append((r - 1, 'unknown', '', '', ''))
    return info


def find_rows_to_delete(row_info, fp_triples):
    """Given classified rows (0-idx) with check_type, find data rows matching FP triple
    (st, tt, check_type) + orphan headers. Returns set of 0-indexed row numbers to delete."""
    delete_set = set()

    for entry in row_info:
        if entry[1] == 'data':
            r, _, st, tt, ct = entry
            if (st, tt, ct) in fp_triples:
                delete_set.add(r)

    # orphan headers + unknown-type rows (e.g. ALLUPPERCASE Mismatch)
    for i, entry in enumerate(row_info):
        if entry[1] not in ('header', 'unknown'):
            continue
        r = entry[0]
        has_data = False
        for j in range(i + 1, len(row_info)):
            nxt = row_info[j]
            if nxt[1] in ('header', 'unknown'):
                break
            if nxt[1] == 'data' and nxt[0] not in delete_set:
                has_data = True
                break
        if not has_data:
            delete_set.add(r)

    return delete_set


# ═══════════════════════════════════════════════════════════════
# Deletion (format-specific, preserves formatting)
# ═══════════════════════════════════════════════════════════════

def delete_rows_xls(filepath, delete_set_0idx):
    """Delete rows from .xls using Excel COM (preserves all formatting)."""
    import win32com.client
    for progid in ("Excel.Application", "Ket.Application"):
        try:
            excel = win32com.client.Dispatch(progid)
            break
        except Exception:
            continue
    else:
        raise RuntimeError("No Excel COM available")
    excel.Visible = False
    excel.DisplayAlerts = False
    filepath = os.path.abspath(filepath)
    try:
        wb = excel.Workbooks.Open(filepath)
        ws = wb.Worksheets(1)
        for r in sorted(delete_set_0idx, reverse=True):
            ws.Rows(r + 1).Delete()
        wb.Save()
        wb.Close()
    finally:
        excel.Quit()


def delete_rows_xlsx(filepath, delete_set_0idx):
    """Delete rows from .xlsx using openpyxl (preserves formatting)."""
    import openpyxl
    wb = openpyxl.load_workbook(filepath)
    ws = _pick_sheet_openpyxl(wb)
    for r in sorted(delete_set_0idx, reverse=True):
        ws.delete_rows(r + 1)
    wb.save(filepath)


def _pick_sheet_openpyxl(wb):
    for sn in wb.sheetnames:
        if "xbench" in sn.lower() or "qa" in sn.lower():
            return wb[sn]
    return wb.active


# ═══════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════

def main():
    sys.stdout.reconfigure(encoding='utf-8')

    parser = argparse.ArgumentParser(description='从Xbench报告中删除对照文件标记为误报的条目')
    parser.add_argument('--ref', required=True, help='对照文件（Comments列含误报标注）')
    parser.add_argument('--input', required=True, help='待处理文件')
    parser.add_argument('--output', help='输出路径（默认: 输入_cleaned.ext）')
    args = parser.parse_args()

    ref_ext = os.path.splitext(args.ref)[1].lower()
    input_ext = os.path.splitext(args.input)[1].lower()
    is_xls = input_ext == '.xls'

    if not args.output:
        base, ext = os.path.splitext(args.input)
        args.output = f"{base}_cleaned{ext}"

    # ── 1. 提取对照文件 FP triples ──
    if ref_ext == '.xls':
        import xlrd
        wb = xlrd.open_workbook(args.ref)
        ws = wb.sheet_by_index(0)
        fp_triples = get_fp_triples_xlrd(ws)
        wb.release_resources()
    else:
        import openpyxl
        wb = openpyxl.load_workbook(args.ref, data_only=True)
        ws = _pick_sheet_openpyxl(wb)
        fp_triples = get_fp_triples_openpyxl(ws)
        wb.close()

    print(f'对照文件误报条目: {len(fp_triples)} 组 (st,tt,check_type)')

    if not fp_triples:
        print('对照文件中无匹配标记，无需处理。')
        return

    # ── 2. 分析待处理文件，找出要删的行 ──
    if is_xls:
        import xlrd
        wb = xlrd.open_workbook(args.input)
        ws = wb.sheet_by_index(0)
        row_info = classify_rows_xlrd(ws)
        wb.release_resources()
    else:
        import openpyxl
        wb = openpyxl.load_workbook(args.input)
        ws = _pick_sheet_openpyxl(wb)
        row_info = classify_rows_openpyxl(ws)
        wb.close()

    delete_set = find_rows_to_delete(row_info, fp_triples)

    if not delete_set:
        print('待处理文件中无匹配行，无需删除。')
        return

    data_deleted = sum(1 for e in row_info if e[1] == 'data' and e[0] in delete_set)
    header_deleted = sum(1 for e in row_info if e[1] == 'header' and e[0] in delete_set)
    print(f'删除: {len(delete_set)} 行 (数据行 {data_deleted} + 孤立标题行 {header_deleted})')

    # ── 3. 复制待处理文件 → 在副本上删行 ──
    shutil.copy2(args.input, args.output)

    if is_xls:
        delete_rows_xls(args.output, delete_set)
    else:
        delete_rows_xlsx(args.output, delete_set)

    print(f'输出 → {args.output}')


if __name__ == '__main__':
    main()
